Project/TheTripper/src/TheTripper/Models/Trip.cs
using System;
using System.Collections.Generic;

namespace TheTripper.Models
{
    public class Trip
    {
        public int Id { get; set; }
        
        public string Name { get; set; }

        public DateTime DateCreated { get; set; }

        public string UserName { get; set; }

        public ICollection<Stop> Stops { get; set; }
    }
}

Project/TheTripper/src/TheTripper/ViewModels/ContactViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace TheTripper.ViewModels
{
    public class ContactViewModel
    {
        [Required]
        public string Name { get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [StringLength(1024, MinimumLength = 5)]
        public string Subject { get; set; }

        [Required]
        [StringLength(4096, MinimumLength = 10)]
        public string Message { get; set; }
    }
}

Project/TheTripper/src/TheTripper/ViewModels/TripViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TheTripper.ViewModels
{
    public class TripViewModel
    {
        [Required]
        [StringLength(100, MinimumLength = 5)]
        public string Name { get; set; }

        public DateTime DateCreated { get; set; } = DateTime.UtcNow;
    }
}

Project/TheTripper/src/TheTripper/Controllers/Api/TripsController.cs
using TheTripper.Models;
using TheTripper.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace TheTripper.Controllers.Api
{
    [Route("api/trips")]
    [Authorize]
    public class TripsController : Controller
    {
        private ILogger<TripsController> _logger;
        private IWorldRepository _repository;

        public TripsController(IWorldRepository repository, ILogger<TripsController> logger)
        {
            _repository = repository;
            _logger = logger;
        }

        [HttpGet("")]
        public IActionResult Get()
        {
            try
            {
                IEnumerable<Trip> results = _repository.GetTripsByUsername(User.Identity.Name);

                return Ok(AutoMapper.Mapper.Map<IEnumerable<TripViewModel>>(results));
            }
            catch (System.Exception ex)
            {
                _logger.LogError($"Failed to get All Trips: {ex}");
                return BadRequest("Error occured");
            }
        }

        [HttpPost("")]
        public async Task<IActionResult> Post([FromBody]TripViewModel trip)
        {
            if (ModelState.IsValid)
            {
                Trip newTrip = AutoMapper.Mapper.Map<Trip>(trip);

                newTrip.UserName = User.Identity.Name;

                _repository.AddTrip(newTrip);

                if(await _repository.SaveChangesAsync())
                {
                    return Created($"api/trips/{trip.Name}", AutoMapper.Mapper.Map<TripViewModel>(newTrip));
                }
                else
                {
                    return BadRequest("Failed to save changes to the database");
                }
            }

            return BadRequest("Failed to save the trip");
        }
    }
}

Project/TheTripper/src/TheTripper/Controllers/Web/AppController.cs
using System.Collections.Generic;
using System.Linq;
using TheTripper.Models;
using TheTripper.Services;
using TheTripper.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Authorization;

namespace TheTripper.Controllers.Web
{
    public class AppController : Controller
    {
        private IMailService _mailService;
        private IConfigurationRoot _config;
        private IWorldRepository _repository;
        private ILogger<AppController> _logger;

        public AppController(IMailService mailService, IConfigurationRoot config, IWorldRepository repository, ILogger<AppController> logger)
        {
            _mailService = mailService;
            _config = config;
            _repository = repository;
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Contact(ContactViewModel model)
        {
            if (ModelState.IsValid)
            {
                _mailService.SendMail(_config["MailSettings:ToAddress"], model.Email, model.Subject, model.Message);

                ModelState.Clear();

                ViewBag.UserMessage = "Message sent";
            }

            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        [Authorize]
        public IActionResult Trips()
        {
            string googleKey = _config["Keys:GoogleKey"];
            ViewBag.GoogleKey = googleKey;

            return View();
        }
    }
}

Project/TheTripper/src/TheTripper/Views/App/About.cshtml
@{
    ViewBag.Title = "About Page";
}

<h2>About</h2>

<p>This application allows you to plan or review your Trips.</p>

Project/TheTripper/src/TheTripper/Views/App/Contact.cshtml
@model TheTripper.ViewModels.ContactViewModel

@{
    ViewBag.Title = "Contact Page";
}

@section scripts{
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h2>Contact me!</h2>
        <form method="post">
            <span asp-validation-summary="ModelOnly" class="text-muted"></span>
            @if (ViewBag.UserMessage != null)
            {
                <div>@ViewBag.UserMessage</div>
            }

            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-muted"></span>
            </div>

            <div class="form-group">
                <label asp-for="Email">Email</label>
                <input type="email" asp-for="Email" class="form-control"/>
                <span asp-validation-for="Email" class="text-muted"></span>
            </div>

            <div class="form-group">
                <label asp-for="Subject"></label>
                <input asp-for="Subject" class="form-control" />
                <span asp-validation-for="Subject" class="text-muted"></span>
            </div>

            <div class="form-group">
                <label asp-for="Message"></label>
                <textarea cols="40" rows="4" asp-for="Message" class="form-control"></textarea>
                <span asp-validation-for="Message" class="text-muted"></span>
            </div>

            <div class="form-group">
                <a asp-controller="App" asp-action="Index" class="btn btn-default">Cancel</a>
                <input type="submit" value="Send Message" class="btn btn-success"/>
            </div>
        </form>
    </div>
</div>

Project/TheTripper/src/TheTripper/Views/App/Index.cshtml
@model IEnumerable<TheTripper.Models.Trip>
@{ 
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div class="col-md-12">
        <h1>Welcome to the Trips Planner</h1>
        <p>This app will allow you to plan your trips</p>
        <a asp-controller="App" asp-action="Trips" class="btn btn-lg btn-success">View my trips</a>
    </div>
</div>

Project/TheTripper/src/TheTripper/Views/App/Trips.cshtml
@{
    ViewBag.Title = "Trips Page";
}
@section Scripts{
    <script src="~/lib/underscore/underscore-min.js"></script>
    <script src="~/lib/angular/angular.min.js"></script>
    <script src="~/lib/angular-route/angular-route.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=@ViewBag.GoogleKey"></script>
    <script src="~/lib/travelmap/travelmap.min.js"></script>
    <script src="~/lib/gmaps/gmaps.min.js"></script>
    <script src="~/js/app-trips.js"></script>
    <script src="~/js/tripsController.js"></script>
    <script src="~/js/tripEditorController.js"></script>
}
<div class="row" ng-app="app-trips">

    <div ng-view></div>

</div>