Project/TheTripper/src/TheTripper/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using TheTripper.Models;
using TheTripper.ViewModels;

namespace TheTripper.Controllers
{
    public class AuthController : Controller
    {
        private SignInManager<WorldUser> _signInManager;

        public AuthController(SignInManager<WorldUser> signInManager)
        {
            _signInManager = signInManager;
        }

        public IActionResult Login()
        {
            if(User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Trpis", "App");
            }

            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Login(LoginViewModel loginViewModel, string returnUrl)
        {
            if(ModelState.IsValid)
            {
                var signInResult = await _signInManager.PasswordSignInAsync(loginViewModel.Username,
                                                                            loginViewModel.Password,
                                                                            true, false);

                if(signInResult.Succeeded)
                {
                    if (string.IsNullOrWhiteSpace(returnUrl))
                        return RedirectToAction("Trips", "App");
                    else
                        return Redirect(returnUrl);
                }
                else
                {
                    ModelState.AddModelError("", "Username or password incorrect");
                }
            }

            return View();
        }

        public async Task<ActionResult> Logout()
        {
            if(User.Identity.IsAuthenticated)
            {
                await _signInManager.SignOutAsync();
            }

            return RedirectToAction("Index", "App");
        }
    }
}

Project/TheTripper/src/TheTripper/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <title>The World @ViewBag.Title</title>
    <meta charset="utf-8" />

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/lib/bootswatch/readable/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>

<body>
    <div id="sidebar">
        @if (User.Identity.IsAuthenticated)
        {
            <img src="~/img/Wojciech Dąbrowski - zdjęcie 3,5x4,5.jpg" alt="headshot" class="headshot" />
            <span id="username">@User.Identity.Name</span>
        }

        <ul class="nav">
            <li class="active"><a asp-controller="App" asp-action="Index">Home</a></li>
            <li><a asp-controller="App" asp-action="About">About</a></li>
            <li><a asp-controller="App" asp-action="Contact">Contact</a></li>
            @if (User.Identity.IsAuthenticated)
            {
                <li><a asp-controller="App" asp-action="Trips">Trips</a></li>
                <li><a asp-controller="Auth" asp-action="Logout">Logout</a></li>
            }
        </ul>
    </div>

    <div id="site-wrapper">
        <nav class="navbar navbar-inverse">
            <div>
                <ul class="nav navbar-nav navbar-left">
                    <li>
                        <button id="sidebarToggle" class="btn btn-primary">
                            <i class="fa fa-angle-left"></i>
                        </button>
                    </li>
                </ul>
                <a asp-controller="App" asp-action="Index" class="navbar-brand">The World</a>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#" class="btn btn-sm btn-info">
                            <i class="fa fa-save"></i> Save
                        </a>
                    </li>
                    <li>
                        <a href="#" class="btn btn-sm btn-info">
                            <i class="fa fa-print"></i> Print
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
        <div id="main" class="container-fluid main">
            <div>
                @RenderBody()
            </div>
        </div>
        <div id="footer" class="container-fluid footer">
            <div>
                <h4 class="text-center text-info">&copy; 2017 Wojciech Dąbrowski</h4>
            </div>
        </div>
    </div>

    <script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>

    @RenderSection("scripts", false)

    <script type="text/javascript" src="~/js/site.js"></script>

</body>


</html>